CREATE TABLE VIDEO_CONTENT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CONTENTTYPE VARCHAR(100) NOT NULL,
    CONTENT bytea NOT NULL
);
ALTER TABLE VIDEO_DETAILS ADD CONSTRAINT FK_VIDEO_CONTENT_ID FOREIGN KEY (ID) REFERENCES VIDEO_CONTENT(ID);